<a href="https://colab.research.google.com/github/aleksejalex/2024_ells_python/blob/main/monday/04_lec_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ELLS - Practical Introduction into Programming with Python

<a href="https://pef.czu.cz/en/"><img src="https://aleksejalex.4fan.cz/ells/temp_banner.jpeg?" alt="banner" width="1000"></a>





[GitHub Repository](https://github.com/aleksejalex/2024_ells_python)


# Plan for this lecture:
## NumPy Lecture Outline


## Part 1: Creating NumPy Arrays
- Using `np.array()` to create arrays from Python lists.
- Generating arrays with `np.zeros()` and `np.ones()`.
- Using `np.arange()` for array creation.
- Exploring array attributes (shape, dtype, ndim, size).
- Reshaping arrays with `np.reshape()`.

## Part 2: Array Indexing and Slicing
- Accessing elements and rows in a NumPy array.
- Slicing subarrays in NumPy arrays.
- Using negative indices for indexing.
- Combining indexing and slicing.
- Modifying array elements using indexing.

## Part 3: Array Operations
- Element-wise Operations: Arithmetic operations (+, -, *, /).
- Array Broadcasting: Understanding how NumPy handles operations on arrays of different shapes.

## Part 4: Aggregation Functions
- Basic Aggregation: Computing statistics like min, max, sum, mean.

## Part 5: Advanced Indexing and Filtering
- Boolean Indexing: Selecting elements based on conditions.
- Fancy Indexing: Using integer arrays to access elements.

## Part 6: Advanced NumPy Techniques
- Linear Algebra Operations: Matrix multiplication, determinant, inverse.
- Array Manipulation: Reshaping, stacking, splitting arrays.


## NumPy: Numerical Python

<a href="https://numpy.org/"><img src="https://numpy.org/doc/stable/_static/numpylogo.svg" alt="logo" width="400" align="right"></a>

= library created to work with *numerical data*:

 - effectively stores and operates with high-dimensional data structures (**arrays** - like vectors and matrices)
 - implements mathematical operations on those arrays

### Array - basic type of variable in NumPy

 - very similar to vector/matrix in algebra
 - type of variable: `ndarray`

| Feature                          | Python Lists (`list`)                                 | NumPy Arrays (`ndarray`)                                 |
|----------------------------------|-----------------------------------------------|----------------------------------------------|
| Data Types                       | Can contain elements of different data types  | Homogeneous data type ⚠️                       |
| Performance                      | Slower for large datasets                     | Faster for large datasets                    |
| Mathematical Operations          | Limited functionality for mathematical ops    | Rich set of mathematical operations         |
| Indexing and Slicing             | Basic indexing and slicing                    | Advanced indexing and slicing                |
| Iteration                        | Basic iteration                                | Vectorized operations                        |
| Memory Efficiency                | Less memory efficient                         | More memory efficient                        |


# Part 1: Creating NumPy Arrays

### 1. Using `np.array()` to Create Arrays from Python Lists

NumPy arrays can be created from Python lists using the `np.array()` function. This function takes a list (or nested lists for multi-dimensional arrays) and converts it into a NumPy array.


In [2]:
import numpy as np

# Creating a NumPy array from a list
list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)

print("1D Array from list:", array_1d)

1D Array from list: [1 2 3 4 5]


...something we are familiar with from math and physics:

$$ \vec{a} = \begin{pmatrix} 1 \\ 2 \\ 3 \\ 4 \\ 5 \end{pmatrix} $$

### 2. Generating Arrays with `np.zeros()` and `np.ones()`

NumPy provides convenient functions to create arrays filled with zeros or ones.


In [3]:
# Generating a 3x3 array filled with zeros
zeros_array = np.zeros((3, 3))

print("3x3 Array of zeros:\n", zeros_array)

# Generating a 2x5 array filled with ones
ones_array = np.ones((2, 5))

print("2x5 Array of ones:\n", ones_array)

3x3 Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2x5 Array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### 3. Using `np.arange()` for Array Creation

The `np.arange()` function generates arrays with evenly spaced values within a specified range.


In [4]:
# Creating an array from 10 to 50 with a step of 5
arange_array = np.arange(10, 55, 5)

print("Array with np.arange(10, 55, 5):", arange_array)


Array with np.arange(10, 55, 5): [10 15 20 25 30 35 40 45 50]


### 4. Exploring Array Attributes (shape, dtype, ndim, size)

NumPy arrays have several attributes that provide information about the array's structure and data type.


In [5]:
# Creating an array
example_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Exploring array attributes
print("Array:\n", example_array)
print("Shape:", example_array.shape)    # Shape of the array
print("Data type:", example_array.dtype) # Data type of the array elements
print("Number of dimensions:", example_array.ndim) # Number of dimensions
print("Size (number of elements):", example_array.size) # Total number of elements


Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data type: int64
Number of dimensions: 2
Size (number of elements): 9


*Remark:* printing numpy's array:

In [48]:
# common way:
print(example_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
# using benefits of jupyter notebook:
example_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 5. Reshaping Arrays with `np.reshape()`

The `np.reshape()` function allows you to change the shape of an array without changing its data.


In [6]:
# Creating and reshaping an array
original_array = np.arange(12)
reshaped_array = np.reshape(original_array, (3, 4))

print("Original array:", original_array)
print("Reshaped array:\n", reshaped_array)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Part 2: Array Indexing and Slicing

### 1. Accessing elements and rows in a NumPy array

You can access individual elements and entire rows in a NumPy array using indices. NumPy arrays use zero-based indexing, so the first element is accessed with index 0.


In [7]:
import numpy as np

# Creating a 4x4 array
array_4x4 = np.arange(16).reshape(4, 4)

# Accessing the element at 3rd row, 2nd column
element = array_4x4[2, 1]

# Accessing the entire second row
second_row = array_4x4[1, :]

print("4x4 Array:\n", array_4x4)
print("Element at 3rd row, 2nd column:", element)
print("Second row:", second_row)


4x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Element at 3rd row, 2nd column: 9
Second row: [4 5 6 7]


⚠️ Remember: Python indexes from 0.

### 2. Slicing subarrays in NumPy arrays

You can slice subarrays from a NumPy array using the slicing syntax. Slicing is done using the colon (`:`) operator. The syntax is `start:stop:step`, where `start` is the starting index, `stop` is the ending index (exclusive), and `step` is the step size.

In [8]:
# Slicing the first two rows and columns
subarray = array_4x4[:2, :2]

# Slicing every other element in the second row
every_other = array_4x4[1, ::2]

print("4x4 Array:\n", array_4x4)
print("Sliced subarray (first two rows and columns):\n", subarray)
print("Every other element in the second row:", every_other)


4x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sliced subarray (first two rows and columns):
 [[0 1]
 [4 5]]
Every other element in the second row: [4 6]


### 3. Using negative indices for indexing

Negative indices can be used to access elements from the end of the array. For example, `-1` refers to the last element, `-2` refers to the second last element, and so on.


In [9]:
# Accessing the last element using negative indices
last_element = array_4x4[-1, -1]

# Accessing the last row
last_row = array_4x4[-1, :]

print("4x4 Array:\n", array_4x4)
print("Last element (using negative indices):", last_element)
print("Last row (using negative indices):", last_row)


4x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Last element (using negative indices): 15
Last row (using negative indices): [12 13 14 15]


### 4. Combining indexing and slicing

You can combine indexing and slicing to access specific parts of the array. For example, you can access a specific row and then slice elements from that row.


In [10]:
# Combining indexing and slicing to print the second row
second_row_sliced = array_4x4[1, :]

# Slicing elements from the second row
sliced_elements = array_4x4[1, 1:3]

print("4x4 Array:\n", array_4x4)
print("Second row (using slicing):", second_row_sliced)
print("Sliced elements from the second row:", sliced_elements)


4x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Second row (using slicing): [4 5 6 7]
Sliced elements from the second row: [5 6]


### 5. Modifying array elements using indexing

You can modify elements of a NumPy array by using indexing. This can be done for individual elements or for entire rows/columns.

In [11]:
# Modifying the third row to all 10s
array_4x4[2, :] = 10

# Modifying the element at 2nd row, 3rd column to 50
array_4x4[1, 2] = 50

print("Modified array (third row set to 10s and one element to 50):\n", array_4x4)


Modified array (third row set to 10s and one element to 50):
 [[ 0  1  2  3]
 [ 4  5 50  7]
 [10 10 10 10]
 [12 13 14 15]]


# Part 3: Array Operations

### 1. Element-wise Operations: Arithmetic operations (+, -, *, /)

NumPy allows you to perform arithmetic operations on arrays element-wise. This means that the operation is applied to each element of the array individually.


In [12]:
import numpy as np

# Creating two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise division
division = array1 / array2

# Element-wise power
power = array1 ** array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Element-wise addition:", addition)
print("Element-wise subtraction:", subtraction)
print("Element-wise multiplication:", multiplication)
print("Element-wise division:", division)
print("Element-wise power:", power)


Array 1: [1 2 3]
Array 2: [4 5 6]
Element-wise addition: [5 7 9]
Element-wise subtraction: [-3 -3 -3]
Element-wise multiplication: [ 4 10 18]
Element-wise division: [0.25 0.4  0.5 ]
Element-wise power: [  1  32 729]


Element-wise operations also comes in handy when we want to get values of a function (for ex. to plot it).

In [13]:
x = np.arange(0, 5, 1)
print(f"arguments x = {x}")

y = x**2

print(f"values of y=x^2: {y}")

arguments x = [0 1 2 3 4]
values of y=x^2: [ 0  1  4  9 16]


Also there is a variety of built-in functions:

In [14]:
x = 1/2*np.pi
print(f"x = {x}")

print(f"value of sin(x): {np.sin(x)}")
print(f"value of cos(x): {np.cos(x)}")
print(f"value of tan(x): {np.tan(x)}")

x = 1.5707963267948966
value of sin(x): 1.0
value of cos(x): 6.123233995736766e-17
value of tan(x): 1.633123935319537e+16


**Remark:** matrix multiplication - non-element-wise operation:

Let's have these two matrices:

$$ \mathbb{A} =
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix} ,
\quad \quad
\mathbb{B} =
\begin{pmatrix}
5 & 6 \\
7 & 8 \\
\end{pmatrix}
$$



In [15]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])

In [16]:
# dot product
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [17]:
# or equivalently:
A @ B

array([[19, 22],
       [43, 50]])

You can test it by hand 😜:

$$
\mathbb{A} \cdot \mathbb{B} =
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}
\cdot
\begin{pmatrix}
5 & 6 \\
7 & 8 \\
\end{pmatrix}
=
\begin{pmatrix}
19 & 22 \\
43 & 50 \\
\end{pmatrix}
$$

In [18]:
# element-wise product
np.multiply(A, B)

array([[ 5, 12],
       [21, 32]])

In [19]:
# or equivalently:
A * B

array([[ 5, 12],
       [21, 32]])

### 2. Array Broadcasting: Understanding how NumPy handles operations on arrays of different shapes

NumPy's broadcasting feature allows you to perform arithmetic operations on arrays of different shapes. Broadcasting involves expanding the smaller array along the dimensions with size 1 to match the larger array.


In [20]:
# Creating a 2x3 array
array3 = np.array([[1, 2, 3], [4, 5, 6]])

# Creating a 1D array for broadcasting
array4 = np.array([1, 2, 3])

# Broadcasting the 1D array across the 2x3 array
broadcast_addition = array3 + array4

# Broadcasting a scalar across the 2x3 array
broadcast_scalar = array3 * 2

# Creating a 2D array for broadcasting
array5 = np.array([[1], [2]])

# Broadcasting the 2D array across a compatible 2D array
broadcast_multiplication = array3 * array5

# Creating another 1D array for broadcasting
array6 = np.array([10, 20])

# Broadcasting along a different axis
broadcast_addition2 = array5 + array6[:, np.newaxis]

print("2x3 Array:\n", array3)
print("1D Array for addition:", array4)
print("Broadcasted addition result:\n", broadcast_addition)
print("Broadcasted scalar multiplication result:\n", broadcast_scalar)
print("2D Array for multiplication:\n", array5)
print("Broadcasted multiplication result:\n", broadcast_multiplication)
print("1D Array for addition along different axis:", array6)
print("Broadcasted addition along different axis result:\n", broadcast_addition2)


2x3 Array:
 [[1 2 3]
 [4 5 6]]
1D Array for addition: [1 2 3]
Broadcasted addition result:
 [[2 4 6]
 [5 7 9]]
Broadcasted scalar multiplication result:
 [[ 2  4  6]
 [ 8 10 12]]
2D Array for multiplication:
 [[1]
 [2]]
Broadcasted multiplication result:
 [[ 1  2  3]
 [ 8 10 12]]
1D Array for addition along different axis: [10 20]
Broadcasted addition along different axis result:
 [[11]
 [22]]


# Part 4: Aggregation Functions

### 1. Basic Aggregation: Computing statistics like min, max, sum, mean

NumPy provides a variety of functions to perform basic aggregation operations on arrays. These functions help in computing statistics like minimum, maximum, sum, mean, etc.


In [21]:
import numpy as np

# Creating an array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [22]:
# Example 1: Computing the minimum value
min_value = np.min(array)
print("Minimum value in the array:", min_value)

# Example 2: Computing the maximum value
max_value = np.max(array)
print("Maximum value in the array:", max_value)

# Example 3: Computing the sum of all elements
sum_value = np.sum(array)
print("Sum of all elements in the array:", sum_value)

# Example 4: Computing the mean (average) of all elements
mean_value = np.mean(array)
print("Mean of all elements in the array:", mean_value)

# Example 5: Computing the sum of elements along each column
sum_along_columns = np.sum(array, axis=0)
print("Sum of elements along each column:", sum_along_columns)


Minimum value in the array: 1
Maximum value in the array: 9
Sum of all elements in the array: 45
Mean of all elements in the array: 5.0
Sum of elements along each column: [12 15 18]


### 2. basic aggregation:


#### Computing the cumulative sum of all elements
`np.cumsum(array)` returns the cumulative sum of the elements in the array.

#### Computing the mean (average) along each row
`np.mean(array, axis=1)` returns the average of elements in each row.

#### Computing the standard deviation of all elements
`np.std(array)` returns the standard deviation of the elements in the array, which measures the amount of variation or dispersion.

#### Computing the variance of all elements
`np.var(array)` returns the variance of the elements in the array, which is the average of the squared differences from the mean.


In [23]:
import numpy as np

# Creating an array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Example 3: Computing the cumulative sum of all elements
cumulative_sum = np.cumsum(array)
print("Cumulative sum of all elements:", cumulative_sum)

# Example 4: Computing the mean (average) along each row
mean_value_rows = np.mean(array, axis=1)
print("Mean of elements along each row:", mean_value_rows)

# Example 5: Computing the standard deviation of all elements
std_deviation = np.std(array)
print("Standard deviation of all elements:", std_deviation)

# Example 6: Computing the variance of all elements
variance = np.var(array)
print("Variance of all elements:", variance)


Cumulative sum of all elements: [ 1  3  6 10 15 21 28 36 45]
Mean of elements along each row: [2. 5. 8.]
Standard deviation of all elements: 2.581988897471611
Variance of all elements: 6.666666666666667


# Part 5: Advanced Indexing and Filtering

### 1. Boolean Indexing: Selecting elements based on conditions

Boolean indexing allows you to select elements from an array that satisfy certain conditions.


In [24]:
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50, 60])

# Example 1: Selecting elements greater than 30
greater_than_30 = array[array > 30]
print("Elements greater than 30:", greater_than_30)

# Example 2: Selecting elements that are even
even_elements = array[array % 2 == 0]
print("Even elements:", even_elements)

# Example 3: Selecting elements that are less than or equal to 40
less_equal_40 = array[array <= 40]
print("Elements less than or equal to 40:", less_equal_40)

# Example 4: Selecting elements that are between 20 and 50 (inclusive)
between_20_50 = array[(array >= 20) & (array <= 50)]
print("Elements between 20 and 50:", between_20_50)

# Example 5: Selecting elements that are not equal to 30
not_equal_30 = array[array != 30]
print("Elements not equal to 30:", not_equal_30)


Elements greater than 30: [40 50 60]
Even elements: [10 20 30 40 50 60]
Elements less than or equal to 40: [10 20 30 40]
Elements between 20 and 50: [20 30 40 50]
Elements not equal to 30: [10 20 40 50 60]


### 2. Fancy Indexing: Using integer arrays to access elements

Fancy indexing allows you to use arrays of integers to access specific elements from another array.


In [25]:
# Creating an array
array = np.array([10, 20, 30, 40, 50, 60])

# Example 1: Selecting elements at indices 1, 3, and 5
indices = np.array([1, 3, 5])
selected_elements = array[indices]
print("Elements at indices 1, 3, and 5:", selected_elements)

# Example 2: Selecting elements at negative indices -1, -2, and -3
negative_indices = np.array([-1, -2, -3])
selected_negative_elements = array[negative_indices]
print("Elements at negative indices -1, -2, and -3:", selected_negative_elements)

# Example 3: Selecting elements using a 2D index array
index_array_2d = np.array([[0, 2], [1, 3]])
selected_2d_elements = array[index_array_2d]
print("Elements selected using a 2D index array:\n", selected_2d_elements)

# Example 4: Selecting elements at specific positions and setting them to a new value
array[np.array([0, 2, 4])] = 99
print("Array after setting specific positions to 99:", array)

# Example 5: Using fancy indexing with multi-dimensional arrays
multi_dim_array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])
fancy_selected_elements = multi_dim_array[row_indices, col_indices]
print("Elements selected using fancy indexing in a multi-dimensional array:", fancy_selected_elements)


Elements at indices 1, 3, and 5: [20 40 60]
Elements at negative indices -1, -2, and -3: [60 50 40]
Elements selected using a 2D index array:
 [[10 30]
 [20 40]]
Array after setting specific positions to 99: [99 20 99 40 99 60]
Elements selected using fancy indexing in a multi-dimensional array: [30 50 70]


## Part 6: Advanced NumPy Techniques
- Linear Algebra Operations: Matrix multiplication, determinant, inverse.
- Array Manipulation: Reshaping, stacking, splitting arrays.

### 1. Linear Algebra Operations: Matrix multiplication, determinant, inverse

NumPy provides a suite of functions for performing linear algebra operations. These include matrix multiplication, computing the determinant of a matrix, and finding the inverse of a matrix.


In [26]:
import numpy as np

# Creating two matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Example 1: Matrix multiplication
matrix_multiplication = np.dot(matrix_a, matrix_b)
print("Matrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)
print("Matrix multiplication (A * B):\n", matrix_multiplication)

# Example 2: Determinant of a matrix
determinant = np.linalg.det(matrix_a)
print("Determinant of matrix A:", determinant)

# Example 3: Inverse of a matrix
inverse_matrix = np.linalg.inv(matrix_a)
print("Inverse of matrix A:\n", inverse_matrix)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix multiplication (A * B):
 [[19 22]
 [43 50]]
Determinant of matrix A: -2.0000000000000004
Inverse of matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### 2. Array Manipulation: Reshaping, stacking, splitting arrays

NumPy allows you to manipulate arrays in various ways, such as reshaping, stacking, and splitting arrays.


In [43]:
# Creating an array
array = np.arange(1, 13).reshape(3, 4)

# Example 1: Reshaping an array
reshaped_array = array.reshape(4, 3)
print("Original array:\n", array)
print("Reshaped array (4x3):\n", reshaped_array)

# Example 2: Stacking arrays vertically
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
stacked_array = np.vstack((array1, array2))
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Vertically stacked array:\n", stacked_array)

# Example 3: Stacking arrays horizontally
horizontally_stacked_array = np.hstack((array1, array2))
print("Horizontally stacked array:\n", horizontally_stacked_array)
print("\n")

# Example 4: Splitting an array along the second axis (columns)
split_array_columns = np.split(array, 2, axis=1)
print("Array split into 2 sub-arrays along columns:\n", split_array_columns)


Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array (4x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Vertically stacked array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally stacked array:
 [[1 2 5 6]
 [3 4 7 8]]


Array split into 2 sub-arrays along columns:
 [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


# Summary

## Part 1: Creating NumPy Arrays
- Using `np.array()` to create arrays from Python lists.
- Generating arrays with `np.zeros()` and `np.ones()`.
- Using `np.arange()` for array creation.
- Exploring array attributes (shape, dtype, ndim, size).
- Reshaping arrays with `np.reshape()`.

## Part 2: Array Indexing and Slicing
- Accessing elements and rows in a NumPy array.
- Slicing subarrays in NumPy arrays.
- Using negative indices for indexing.
- Combining indexing and slicing.
- Modifying array elements using indexing.

## Part 3: Array Operations
- Element-wise Operations: Arithmetic operations (+, -, *, /).
- Array Broadcasting: Understanding how NumPy handles operations on arrays of different shapes.

## Part 4: Aggregation Functions
- Basic Aggregation: Computing statistics like min, max, sum, mean.

## Part 5: Advanced Indexing and Filtering
- Boolean Indexing: Selecting elements based on conditions.
- Fancy Indexing: Using integer arrays to access elements.

## Part 6: Advanced NumPy Techniques
- Linear Algebra Operations: Matrix multiplication, determinant, inverse.
- Array Manipulation: Reshaping, stacking, splitting arrays.

## Additional sources (where to seek for information):
 - Crash course on YouTube: https://www.youtube.com/watch?v=QUT1VHiLmmI&t=75s
 - w3schools: https://www.w3schools.com/python/numpy/numpy_intro.asp
 - official tutorials: https://numpy.org/doc/stable/

## Bonus

## How to solve $\mathbb{A} \cdot \vec{x} = \vec{b}$?

You definitely remember solving systems of linear equations in primary school.

$$\left\{
\begin{align*}
2x + 3y - z &= 7 \\
4x - 2y + 5z &= 3 \\
x + y - 3z &= -2 \\
\end{align*} \right. $$

At the beginning of your algebra course, you used matrices for the same task:

$$
\mathbb{A} = \begin{pmatrix}
2 & 3 & -1 \\
4 & -2 & 5 \\
1 & 1 & -3 \\
\end{pmatrix}, \quad \vec{b} = \begin{pmatrix} 7 \\ 3 \\ -2 \end{pmatrix}
$$

and you searched for $\vec{x} = \begin{pmatrix} x \\ y \\ z  \end{pmatrix}$ as the solution of $\mathbb{A} \cdot \vec{x} = \vec{b}$.


Mathematical solution: $\vec{x} = \mathbb{A}^{-1} \cdot \vec{b} $

In [28]:
# Let's define A and b from example above using NumPy:
import numpy as np

A = np.array([[2, 3, -1], [4, -2, 5], [1, 1, -3]])
b = np.array([7, 3, -2])

### Aproach 1: do it manually (almost):

In [29]:
x = np.linalg.inv(A) @ b
x

array([0.10638298, 2.80851064, 1.63829787])

In [30]:
# "quality check":
A @ x

array([ 7.,  3., -2.])

### Aproach 2: use NumPy solver:

In [33]:
xx = np.linalg.solve(A, b)
xx

array([0.10638298, 2.80851064, 1.63829787])

In [34]:
# "quality check":
A @ xx

array([ 7.,  3., -2.])

### Comparison: speed?

In [44]:
# approach 1:
%timeit np.linalg.inv(   np.random.rand(3, 3)  ) @ np.random.rand(3, 1)

22.9 µs ± 4.49 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [45]:
# approach 2:
%timeit np.linalg.solve(   np.random.rand(3, 3), np.random.rand(3, 1) )

9.84 µs ± 314 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


🤔 ..not a difference, huh?

Just *wait for it*:

In [46]:
# approach 1:
%timeit np.linalg.inv(   np.random.rand(3000, 3000)  ) @ np.random.rand(3000, 1)

2.92 s ± 325 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [47]:
# approach 2:
%timeit np.linalg.solve(   np.random.rand(3000, 3000), np.random.rand(3000, 1) )

1.07 s ± 269 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


<div style="font-style: italic; font-size: 14px;">
    <p>This material was prepared by Department of Information Engineering (<a href="https://www.pef.czu.cz/en">PEF ČZU</a>) exclusively for purposes of ELLS summer school "Practical Introduction into Programming with Python". Any distribution or reproduction of this material, in whole or in part, without prior written consent of the authors is prohibited.</p>
    <p>This material is shared under the <b>Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License</b>, <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">link</a>.</p>
</div>
