<a href="https://colab.research.google.com/github/aleksejalex/2024_ells_python/blob/main/monday/04_wrk_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ELLS - Practical Introduction into Programming with Python

<a href="https://pef.czu.cz/en/"><img src="https://aleksejalex.4fan.cz/ells/temp_banner.jpeg?" alt="banner" width="1000"></a>





[GitHub Repository](https://github.com/aleksejalex/2024_ells_python)


## NumPy Workshop Outline

<a href="https://numpy.org/"><img src="https://numpy.org/doc/stable/_static/numpylogo.svg" alt="logo" width="400" align="right"></a>= library created to work with *numerical data*:

## Part 1: Creating NumPy Arrays
- Using `np.array()` to create arrays from Python lists.
- Generating arrays with `np.zeros()` and `np.ones()`.
- Using `np.arange()` for array creation.
- Exploring array attributes (shape, dtype, ndim, size).
- Reshaping arrays with `np.reshape()`.

## Part 2: Array Indexing and Slicing
- Accessing elements and rows in a NumPy array.
- Slicing subarrays in NumPy arrays.
- Using negative indices for indexing.
- Combining indexing and slicing.
- Modifying array elements using indexing.

## Part 3: Array Operations
- Element-wise Operations: Arithmetic operations (+, -, *, /).
- Array Broadcasting: Understanding how NumPy handles operations on arrays of different shapes.

## Part 4: Aggregation Functions
- Basic Aggregation: Computing statistics like min, max, sum, mean.

## Part 5: Advanced Indexing and Filtering
- Boolean Indexing: Selecting elements based on conditions.
- Fancy Indexing: Using integer arrays to access elements.

## Part 6: Advanced NumPy Techniques
- Linear Algebra Operations: Matrix multiplication, determinant, inverse.
- Array Manipulation: Reshaping, stacking, splitting arrays.


# Part 1 - Creating NumPy Arrays


### Task 1: Creating and manipulating NumPy arrays
 - Create a NumPy array from the list `[5, 10, 15, 20, 25, 30]`.

 - Then generate a 3x3 array filled with ones and multiply it by 5.

 - Finally, create an array with values ranging from 10 to 50 with a step of 5 and reshape it to a 3x3 array.

 - Print all arrays.


In [7]:
# your code here ...

In [1]:
import numpy as np

# Creating a NumPy array from a list
array_from_list = np.array([5, 10, 15, 20, 25, 30])

# Generating a 3x3 array filled with ones and multiplying it by 5
ones_array = np.ones((3, 3)) * 5

# Creating an array from 10 to 50 with a step of 5 and reshaping it to 3x3
arange_array = np.arange(10, 55, 5).reshape(3, 3)

print("Array from list:", array_from_list)
print("3x3 Array of ones multiplied by 5:\n", ones_array)
print("Array with values from 10 to 50 reshaped to 3x3:\n", arange_array)


Array from list: [ 5 10 15 20 25 30]
3x3 Array of ones multiplied by 5:
 [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
Array with values from 10 to 50 reshaped to 3x3:
 [[10 15 20]
 [25 30 35]
 [40 45 50]]


# Part 2: Array Indexing and Slicing

### Task 1: Advanced Indexing and Slicing
Create a 6x6 array using `np.arange(36).reshape(6, 6)`. Access and print the element at the 5th row, 4th column, the entire third row, and a subarray consisting of the first four rows and last three columns.


In [2]:
import numpy as np

# Creating a 6x6 array
array_6x6 = np.arange(36).reshape(6, 6)

# Accessing elements
element = array_6x6[4, 3]
third_row = array_6x6[2, :]
subarray = array_6x6[:4, 3:]

print("6x6 Array:\n", array_6x6)
print("Element at 5th row, 4th column:", element)
print("Third row:", third_row)
print("Subarray (first four rows, last three columns):\n", subarray)


6x6 Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
Element at 5th row, 4th column: 27
Third row: [12 13 14 15 16 17]
Subarray (first four rows, last three columns):
 [[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]]


# Part 3: Array Operations

### Task 1: Complex Element-wise Operations
Create two 2x3 arrays: `array1 = np.array([[1, 2, 3], [4, 5, 6]])` and `array2 = np.array([[7, 8, 9], [10, 11, 12]])`. Perform element-wise addition, subtraction, multiplication, and division. Then compute the element-wise square root of `array1` and the element-wise exponential of `array2`. Print all results.


In [3]:
import numpy as np

# Creating two arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2
sqrt_array1 = np.sqrt(array1)
exp_array2 = np.exp(array2)

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise addition:\n", addition)
print("Element-wise subtraction:\n", subtraction)
print("Element-wise multiplication:\n", multiplication)
print("Element-wise division:\n", division)
print("Element-wise square root of array1:\n", sqrt_array1)
print("Element-wise exponential of array2:\n", exp_array2)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
Element-wise square root of array1:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Element-wise exponential of array2:
 [[  1096.63315843   2980.95798704   8103.08392758]
 [ 22026.46579481  59874.1417152  162754.791419  ]]


# Part 4: Aggregation Functions

### Task 1: Advanced Aggregation
Create a 4x4 array using `np.array([[2, 3, 5, 7], [11, 13, 17, 19], [23, 29, 31, 37], [41, 43, 47, 53]])`. Compute and print the minimum, maximum, sum, mean, standard deviation, and variance of the entire array, as well as the sum of elements along each row.


In [4]:
import numpy as np

# Creating a 4x4 array
array = np.array([[2, 3, 5, 7], [11, 13, 17, 19], [23, 29, 31, 37], [41, 43, 47, 53]])

# Computing aggregation functions
min_value = np.min(array)
max_value = np.max(array)
sum_value = np.sum(array)
mean_value = np.mean(array)
std_deviation = np.std(array)
variance = np.var(array)
sum_along_rows = np.sum(array, axis=1)

print("Array:\n", array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Sum of all elements:", sum_value)
print("Mean of all elements:", mean_value)
print("Standard deviation:", std_deviation)
print("Variance:", variance)
print("Sum of elements along each row:", sum_along_rows)


Array:
 [[ 2  3  5  7]
 [11 13 17 19]
 [23 29 31 37]
 [41 43 47 53]]
Minimum value: 2
Maximum value: 53
Sum of all elements: 381
Mean of all elements: 23.8125
Standard deviation: 16.206552494284526
Variance: 262.65234375
Sum of elements along each row: [ 17  60 120 184]


# Part 5: Advanced Indexing and Filtering

### Task 1: Boolean and Fancy Indexing
Create a NumPy array `[5, 15, 25, 35, 45, 55, 65]`. Use Boolean indexing to select elements greater than 20. Use fancy indexing to select elements at indices `[0, 2, 4, 6]` and print the results.


In [5]:
import numpy as np

# Creating an array
array = np.array([5, 15, 25, 35, 45, 55, 65])

# Boolean indexing
greater_than_20 = array[array > 20]

# Fancy indexing
fancy_indices = array[[0, 2, 4, 6]]

print("Array:", array)
print("Elements greater than 20:", greater_than_20)
print("Elements at indices [0, 2, 4, 6]:", fancy_indices)


Array: [ 5 15 25 35 45 55 65]
Elements greater than 20: [25 35 45 55 65]
Elements at indices [0, 2, 4, 6]: [ 5 25 45 65]


# Part 6: Advanced NumPy Techniques

### Task 1: Linear Algebra and Array Manipulation
Create a 2x2 matrix `matrix = np.array([[2, 3], [1, 4]])`. Compute and print the determinant and inverse of the matrix. Then create a 1x4 array `[10, 20, 30, 40]`, reshape it to a 2x2 array, and stack it vertically with the original matrix. Finally, split the stacked array into two equal arrays and print all results.


In [6]:
import numpy as np

# Creating a 2x2 matrix
matrix = np.array([[2, 3], [1, 4]])

# Linear algebra operations
determinant = np.linalg.det(matrix)
inverse_matrix = np.linalg.inv(matrix)

# Creating and reshaping an array
array = np.array([10, 20, 30, 40]).reshape(2, 2)

# Stacking arrays
stacked_array = np.vstack((matrix, array))

# Splitting the stacked array
split_arrays = np.split(stacked_array, 2)

print("Matrix:\n", matrix)
print("Determinant of the matrix:", determinant)
print("Inverse of the matrix:\n", inverse_matrix)
print("Reshaped array:\n", array)
print("Stacked array:\n", stacked_array)
print("Split arrays:\n", split_arrays[0], "\n\n", split_arrays[1])


Matrix:
 [[2 3]
 [1 4]]
Determinant of the matrix: 5.000000000000001
Inverse of the matrix:
 [[ 0.8 -0.6]
 [-0.2  0.4]]
Reshaped array:
 [[10 20]
 [30 40]]
Stacked array:
 [[ 2  3]
 [ 1  4]
 [10 20]
 [30 40]]
Split arrays:
 [[2 3]
 [1 4]] 

 [[10 20]
 [30 40]]


# Summary
- Part 1: Creating NumPy Arrays
- Part 2: Array Indexing and Slicing
- Part 3: Array Operations
- Part 4: Aggregation Functions
- Part 5: Advanced Indexing and Filtering
- Part 6: Advanced NumPy Techniques


<div style="font-style: italic; font-size: 14px;">
    <p>This material was prepared by Department of Information Engineering (<a href="https://www.pef.czu.cz/en">PEF ČZU</a>) exclusively for purposes of ELLS summer school "Practical Introduction into Programming with Python". Any distribution or reproduction of this material, in whole or in part, without prior written consent of the authors is prohibited.</p>
    <p>This material is shared under the <b>Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License</b>, <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">link</a>.</p>
</div>
